ALL:QuotoCite OverloadedFunction default namespace auto
auto:auto.cpp
	g++ -g $^ -o $@
QuotoCite:QuotoCite.cpp
	g++ -g $^ -o $@
OverloadedFunction:OverloadedFunction.cpp
	g++ -g $^ -o $@
default:default.cpp
	g++ -g $^ -o $@
namespace:namespace.cpp
	g++ -g $^ -o $@
